"""
Orchestrates semantic, structural, and exact keyword searches across the code graph database,
determines the routing intent, builds context payloads for local LLM consumption, 
and streams final synthesized responses with telemetry.
"""

import os
import asyncio
import re
import shutil
import subprocess
import json
import networkx as nx
from semantic_kernel.functions import KernelArguments
from pathlib import Path
from tenacity import retry, wait_exponential, stop_after_attempt
from semantic_kernel.connectors.ai.open_ai import OpenAIChatPromptExecutionSettings

from utils.constants import AllowedTypes
from utils.logger import get_logger
from utils.helper import timeit, validate_ingestion_path, secure_path_join
from intelligence_layer.kernel_client import LocalKernelFactory
from core.vector_operations import HybridVectorStore
from intelligence_layer.kernel_client import CodebaseSearchPlugin
from utils.global_cache import load_graph_cached
from utils.helper import get_ignore_spec
from intelligence_layer.prompts import (
    GRAPH_RAG_PROMPT, 
    AGENT_PROMPT, 
    KEYWORD_EXTRACTION_PROMPT,
    ROUTER_PROMPT,
    CONSOLIDATION_PROMPT
)

logger = get_logger()


def score_line_match(line: str, matched_word: str, file_path: str) -> float:
    """
    Scores the relevance of a line match based on the matched word/pattern and file type.
    """
    line_lower = line.lower()
    word_lower = matched_word.lower()
    
    # 1. Check file extension first
    ext = os.path.splitext(file_path)[1].lower()
    is_source_file = ext in {'.py', '.js', '.jsx', '.ts', '.tsx', '.go', '.rs', '.c', '.cpp', '.h', '.java', '.kt', '.sh', '.pyw', '.rb', '.pl', '.pm', '.php', '.sql'}
    
    # Base weight based on file type
    base_weight = 1.0 if is_source_file else 0.2
    
    # Apply demotion for prompts or docs files specifically
    if "prompt" in file_path.lower():
        base_weight *= 0.1
    
    # 2. Check if the line is a comment or docstring
    stripped = line.strip()
    is_comment = False
    
    # Common comment patterns
    if stripped.startswith('#') or stripped.startswith('//') or stripped.startswith('*') or stripped.startswith('/*') or stripped.startswith('autogenerated'):
        is_comment = True
    
    # Check if the matched word appears after a comment character
    if '#' in line:
        before_comment = line.split('#', 1)[0]
        if word_lower not in before_comment.lower():
            is_comment = True
    if '//' in line:
        before_comment = line.split('//', 1)[0]
        if word_lower not in before_comment.lower():
            is_comment = True

    # 3. Check if it is inside quotes (string literal)
    is_quoted = f"'{word_lower}'" in line_lower or f'"{word_lower}"' in line_lower
    
    # 4. Check for active code characteristics:
    is_active_code = False
    if is_source_file and not is_comment and not is_quoted:
        # Check patterns with word_lower
        patterns = [
            rf"\bimport\s+{re.escape(word_lower)}\b",
            rf"\bfrom\s+\S+\s+import\s+.*{re.escape(word_lower)}",
            rf"\bdef\s+{re.escape(word_lower)}\b",
            rf"\bclass\s+{re.escape(word_lower)}\b",
            rf"\b{re.escape(word_lower)}\s*\(",
            rf"\b{re.escape(word_lower)}\s*=",
            rf"\.\s*{re.escape(word_lower)}\b",  # e.g. cv2.HoughCircles
            rf"\b{re.escape(word_lower)}\s*as\s+\w+" # e.g. import networkx as nx
        ]
        if any(re.search(pat, line_lower) for pat in patterns):
            is_active_code = True
            
    # Calculate multiplier
    if is_active_code:
        multiplier = 1.0
    elif is_comment or is_quoted:
        multiplier = 0.15 if is_source_file else 0.05
    else:
        multiplier = 0.5 if is_source_file else 0.1
        
    return base_weight * multiplier


class GraphQueryEngine:
    """
    The main Graph query engine that loads graph data, determines user intent,
    routes the query, extracts modular code context, and interfaces with the LLM.
    """
    def __init__(self, repo_name: str, target_repo_path: str):
        self.repo_name = repo_name
        self.graph_path = f".localgraph/storage/{repo_name}/graph.graphml"
        self.kernel = LocalKernelFactory.create_kernel()
        self.kernel.add_plugin(CodebaseSearchPlugin(self), plugin_name="Codebase")
        self.vector_store = HybridVectorStore(repo_name)
        self.target_repo_path = str(validate_ingestion_path(target_repo_path))
        
        # Enable caching for faster query result
        self._graph_cache = None
        self._graph_mtime = None
   
   
    async def _extract_search_tokens_via_llm(self, query: str) -> list[str]:
        """Uses a lightweight LLM keyword analyzer to extract code symbols from natural queries."""
        try:
            res = await self.kernel.invoke_prompt(
                prompt=KEYWORD_EXTRACTION_PROMPT,
                arguments=KernelArguments(user_query=query)
            )
            text = str(res).strip()
            # Clean JSON markdown if present
            if text.startswith("```"):
                lines = text.splitlines()
                if len(lines) >= 2:
                    if lines[0].startswith("```"):
                        lines = lines[1:]
                    if lines[-1].startswith("```"):
                        lines = lines[:-1]
                text = "\n".join(lines).strip()
            if text.startswith("json"):
                text = text[4:].strip()
            tokens = json.loads(text.strip())
            if isinstance(tokens, list):
                # Filter empty values and normalize
                extracted = [str(t).strip() for t in tokens if t]
                logger.info(f"LLM Extracted Search Tokens: {extracted}")
                return extracted
            elif isinstance(tokens, dict):
                for val in tokens.values():
                    if isinstance(val, list):
                        extracted = [str(t).strip() for t in val if t]
                        logger.info(f"LLM Extracted Search Tokens (from dict): {extracted}")
                        return extracted
            return []
        except Exception as e:
            logger.warning(f"LLM keyword extraction failed: {e}. Falling back to rule-based.")
        return []


    async def _exact_match_search(
        self,
        query: str,
        target_dir: Path,
        ignore_spec,
    ) -> dict:
        """
        Extracts code-like tokens from the natural language query and
        searches for them literally or via split-regex across the workspace.
        Returns {token: {relative_path: {"line_numbers": [line_numbers], "match_score": float}}}.
        Respects the same ignore spec as ingestion.
        Language-agnostic: operates on raw file bytes regardless of language.
        """
        # Common English stop words to filter out from natural language queries
        stopwords = AllowedTypes.STOP_WORDS

        # First, try to extract keywords via LLM agent (Option B)
        tokens = await self._extract_search_tokens_via_llm(query)

        # Fallback to rule-based keyword extraction if LLM fails or returns empty list
        if not tokens:
            # 1. First, extract code-specific patterns (CamelCase, snake_case, dotted names)
            code_tokens = re.findall(
                r'\b[A-Z][a-z]+(?:[A-Z][a-z0-9]+)+\b'     # CamelCase
                r'|\b[a-z][a-z0-9]*(?:_[a-z0-9]+)+\b'      # snake_case
                r'|\b[a-zA-Z_]\w+\.[a-zA-Z_]\w+\b',         # dotted
                query
            )

            # 2. As a fallback, extract any alphanumeric word that isn't a stopword or too short
            all_words = re.findall(r'\b[a-zA-Z_]\w*\b', query)
            fallback_tokens = [w for w in all_words if w.lower() not in stopwords and len(w) > 2]

            tokens = list(set(code_tokens + fallback_tokens))

        if not tokens:
            return {}


        has_rg  = shutil.which("rg") is not None
        results = {}

        for token in tokens:
            matched_lines = []

            # Generate fuzzy split regexes for compound/science words
            split_regex = ""
            if len(token) >= 6 and token.isalnum():
                mid = len(token) // 2
                splits = []
                for idx in range(max(3, mid - 1), min(len(token) - 2, mid + 2)):
                    part1 = token[:idx]
                    part2 = token[idx:]
                    splits.append(f"{re.escape(part1)}.*{re.escape(part2)}")
                split_regex = "|".join(splits)

            pattern = f"{re.escape(token)}|{split_regex}" if split_regex else re.escape(token)
            try:
                rx = re.compile(pattern, re.IGNORECASE)
            except Exception:
                rx = re.compile(re.escape(token), re.IGNORECASE)

            if has_rg:
                try:
                    if split_regex:
                        # Run regex search
                        out = subprocess.check_output(
                            ["rg", "-in", "--no-heading", pattern, str(target_dir)],
                            text=True,
                            timeout=5,
                            stderr=subprocess.DEVNULL
                        )
                    else:
                        # Run literal search
                        out = subprocess.check_output(
                            ["rg", "-in", "--no-heading", "-F", token, str(target_dir)],
                            text=True,
                            timeout=5,
                            stderr=subprocess.DEVNULL
                        )
                    matched_lines = out.strip().splitlines()
                except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
                    matched_lines = []
            else:
                # Pure-Python fallback — case-insensitive match
                for file_path in target_dir.rglob("*"):
                    if not file_path.is_file():
                        continue
                    try:
                        rel = str(file_path.relative_to(target_dir))
                    except ValueError:
                        continue
                    if ignore_spec.match_file(rel):
                        continue
                    try:
                        content = file_path.read_text(encoding="utf-8", errors="ignore")
                        for i, line in enumerate(content.splitlines(), 1):
                            matched = False
                            matched_word = token
                            if rx:
                                m = rx.search(line)
                                if m:
                                    matched = True
                                    matched_word = m.group(0)
                            else:
                                if token.lower() in line.lower():
                                    matched = True
                            if matched:
                                matched_lines.append(f"{file_path}:{i}:{line}")
                    except Exception:
                        continue

            token_results = {}
            for raw in matched_lines:
                parts = raw.split(":", 2)
                if len(parts) < 2:
                    continue
                try:
                    abs_path = Path(parts[0])
                    line_no  = int(parts[1])
                    rel_path = str(abs_path.relative_to(target_dir))
                except (ValueError, Exception):
                    continue
                if ignore_spec.match_file(rel_path):
                    continue

                line_content = parts[2] if len(parts) >= 3 else ""
                matched_word = token
                if line_content and rx:
                    m = rx.search(line_content)
                    if m:
                        matched_word = m.group(0)

                line_score = score_line_match(line_content, matched_word, rel_path)
                file_info = token_results.setdefault(rel_path, {"line_numbers": [], "match_score": 0.0})
                file_info["line_numbers"].append(line_no)
                file_info["match_score"] = max(file_info["match_score"], line_score)
            
            if token_results:
                results[token] = token_results

        return results
        
    async def _get_relevant_subgraph(self, G: nx.Graph, query: str, chat_history: str = "", top_k: int = 15) -> tuple[nx.Graph, dict]:
        """Calculates PageRank score distributions and extracts a relevant semantic subgraph."""
        search_query = query
        if chat_history:
            try:
                # Use LLM to consolidate query with history in a single short sentence
                arguments = KernelArguments(
                    chat_history=chat_history,
                    query=query
                )
                decision = await self.kernel.invoke_prompt(prompt=CONSOLIDATION_PROMPT, arguments=arguments)
                consolidated = str(decision).strip()
                if consolidated:
                    search_query = consolidated
                    logger.info(f"Consolidated Standalone Query: {search_query}")
            except Exception as e:
                logger.warning(f"Query consolidation failed: {e}. Falling back to combined query.")
                # Fallback: combine last user message and current query
                user_queries = []
                for line in chat_history.splitlines():
                    if line.startswith("User:"):
                        user_queries.append(line.replace("User:", "").strip())
                if user_queries:
                    search_query = f"{user_queries[-1]} {query}"

        # 1. Fetch relevant nodes from the hybrid vector store index
        vector_hits = self.vector_store.search(search_query, top_k=top_k)
        
        # 2. Add seed nodes
        seed_nodes = {}
        for hit in vector_hits:
            node_id = hit["node_id"]
            if node_id in G:
                seed_nodes[node_id] = max(seed_nodes.get(node_id, 0), hit["score"])

        # 3. Handle exact filename matches in vector store
        query_words = re.findall(r"\w+", search_query.lower())
        for node_id, data in G.nodes(data=True):
            if data.get("type") == "file":
                node_name = Path(str(node_id).replace("file::", "")).name.lower()
                for qw in query_words:
                    if len(qw) > 3 and qw in node_name:
                        seed_nodes[node_id] = max(seed_nodes.get(node_id, 0), 0.9)

        if not seed_nodes:
            logger.warning("Zero vector seeds found. Grabbing top graph components by degree centrality.")
            degree_dict = dict(G.degree())
            top_nodes = sorted(degree_dict, key=degree_dict.get, reverse=True)[:top_k]
            subgraph_nodes = set(top_nodes)
            scores = {n: 1.0 for n in top_nodes}
            return G.subgraph(subgraph_nodes), scores

        total_score = sum(seed_nodes.values())
        personalization = {node: score / total_score for node, score in seed_nodes.items()}

        try:
            calc_graph = nx.DiGraph(G) if G.is_directed() else nx.Graph(G) if G.is_multigraph() else G
            pr_scores = nx.pagerank(calc_graph, alpha=0.85, personalization=personalization, max_iter=100)

            target_expansion_limit = top_k * 3
            top_structural_nodes = sorted(pr_scores, key=pr_scores.get, reverse=True)[:target_expansion_limit]
            subgraph_nodes = set(top_structural_nodes)
            scores = {n: pr_scores.get(n, 0) for n in subgraph_nodes}
            
            logger.info(f"Successfully generated structural PPR subgraph with {len(subgraph_nodes)} nodes.")
            return G.subgraph(subgraph_nodes), scores

        except Exception as e:
            logger.warning(f"PageRank computation failed or bypassed: {e}. Falling back to 1-hop neighborhood.")
            top_nodes = sorted(seed_nodes, key=seed_nodes.get, reverse=True)[:top_k]
            subgraph_nodes = set(top_nodes)
            scores = {n: seed_nodes.get(n, 0) for n in top_nodes}
            for node in top_nodes:
                neighbors = (set(G.successors(node)) | set(G.predecessors(node))) if G.is_directed() else set(G.neighbors(node))
                subgraph_nodes.update(neighbors)
                for n in neighbors:
                    scores.setdefault(n, 0.1)
            return G.subgraph(subgraph_nodes), scores
        
        
    async def _load_graph(self) -> nx.MultiDiGraph:
        """Loads and returns the in-memory cached graph instance."""
        return await load_graph_cached(self.graph_path)
   
   
    def _extract_semantic_summaries(self, filtered_G: nx.Graph) -> list[str]:
        """Helper to extract and format structural/semantic summaries from subgraph nodes."""
        lines = []
        for node_id, data in filtered_G.nodes(data=True):
            if summary := data.get("summary", ""):
                lines.append(f"- [{data.get('type', 'unknown').upper()}] {node_id}: {summary}")
        return lines


    def _run_structural_ast_search(self, user_query: str, G: nx.Graph) -> list[str]:
        """Helper to run dynamic tree-sitter template parsing and graph queries on the fly."""
        structural_findings = []
        try:
            from core.ast_searcher import ASTSearcher
            searcher = ASTSearcher(G)
            
            # A. Detect inheritance query (e.g. subclass of BaseModel)
            inherit_match = re.search(r"(?:inherits?\s+from|subclass\s+of|extends?)\s+([a-zA-Z_]\w*)", user_query, re.IGNORECASE)
            if inherit_match:
                base_class = inherit_match.group(1)
                matches = searcher.query_graph_structure({"inherits": base_class})
                if matches:
                    structural_findings.append(f"- Classes inheriting from '{base_class}': " + ", ".join([m["id"] for m in matches]))
                    
            # B. Detect calls query (e.g. what calls trigger_ingest)
            call_match = re.search(r"(?:calls?|invokes?|uses?|calling)\s+([a-zA-Z_]\w*)", user_query, re.IGNORECASE)
            if call_match:
                target_symbol = call_match.group(1)
                matches = searcher.query_graph_structure({"calls": target_symbol})
                if matches:
                    structural_findings.append(f"- Components invoking/calling '{target_symbol}': " + ", ".join([m["id"] for m in matches]))
                    
            # C. Detect template query patterns
            for template_name in ["decorators", "exception_handlers", "async_functions", "try_catch", "interfaces"]:
                if template_name.replace("_", " ") in user_query.lower() or template_name in user_query.lower():
                    ext = ".py"
                    if "javascript" in user_query.lower() or "js" in user_query.lower():
                        ext = ".js"
                    elif "typescript" in user_query.lower() or "ts" in user_query.lower():
                        ext = ".ts"
                    elif "tsx" in user_query.lower():
                        ext = ".tsx"
                        
                    matches = searcher.search_tree_sitter_pattern(self.target_repo_path, template_name, ext)
                    if matches:
                        structural_findings.append(f"- Occurrences of structural pattern '{template_name}' found via dynamic AST search:")
                        for m in matches[:10]:
                            structural_findings.append(f"  * File: {m['file_path']} (Lines {m['start_line']}-{m['end_line']})")
                            
        except Exception as e:
            logger.warning(f"Auto AST search query failed: {e}")
        return structural_findings


    def _extract_relationships(self, filtered_G: nx.Graph) -> list[str]:
        """Helper to extract relationships (edges) from the relevant subgraph."""
        lines = []
        for source, target, data in filtered_G.edges(data=True):
            lines.append(f"- {source} explicitly {data.get('relation', 'unknown')} {target}")
        return lines


    async def _extract_raw_source_context(
        self, 
        user_query: str, 
        G: nx.Graph, 
        filtered_G: nx.Graph, 
        relevance_scores: dict, 
        tokens: list[str]
    ) -> list[str]:
        """Helper to find top relevant source code files and extract exact range or snippet code."""
        context_lines = []
        target_dir = Path(self.target_repo_path)
        file_scores = {}
        for node_id, node_data in filtered_G.nodes(data=True):
            file_path = node_data.get("file_path")
            if not file_path:
                node_str = str(node_id)
                if node_str.startswith("file::"):
                    file_path = node_str.replace("file::", "")
                elif "::" in node_str:
                    file_path = node_str.split("::")[0]
            if not file_path:
                continue

            file_path = str(file_path).strip()
            relevance = relevance_scores.get(node_id, 0.0)
            
            # Check if any exact search token is in the node ID or name
            exact_bonus = 0
            for tok in tokens:
                if tok.lower() in str(node_id).lower():
                    exact_bonus = 50
                    break
            node_score = relevance + exact_bonus
            file_scores[file_path] = max(file_scores.get(file_path, 0), node_score)
            
        ignore_spec = get_ignore_spec(target_dir)
        grep_hits = await self._exact_match_search(user_query, target_dir, ignore_spec)
        
        # 1. Group files and their scores by the query token they matched
        token_to_files = {}
        
        # "semantic" token for files with semantic relevance
        semantic_list = sorted(file_scores.items(), key=lambda x: x[1], reverse=True)
        if semantic_list:
            token_to_files["semantic"] = semantic_list
            
        for token, paths_dict in grep_hits.items():
            num_matching_files = len(paths_dict)
            if num_matching_files == 0:
                continue
            if num_matching_files <= 3:
                token_bonus = 300.0 / num_matching_files
            else:
                token_bonus = 100.0 / num_matching_files
            
            token_list = []
            for rel_path, info in paths_dict.items():
                base_score = file_scores.get(rel_path, 0.0)
                match_score = info["match_score"]
                score = base_score + token_bonus * match_score
                token_list.append((rel_path, score))
                file_scores[rel_path] = score
                
            token_list.sort(key=lambda x: x[1], reverse=True)
            token_to_files[token] = token_list

        # 2. Round-robin selection loop to grab top files
        selected_files = []
        selected_set = set()
        active_lists = {token: list(lst) for token, lst in token_to_files.items()}
        
        while len(selected_files) < 5 and active_lists:
            sorted_tokens = sorted(
                active_lists.keys(),
                key=lambda t: active_lists[t][0][1] if active_lists[t] else -1.0,
                reverse=True
            )
            
            selected_in_this_pass = False
            for token in sorted_tokens:
                if len(selected_files) >= 8:
                    break
                
                lst = active_lists[token]
                while lst:
                    rel_path, score = lst.pop(0)
                    if rel_path not in selected_set:
                        selected_set.add(rel_path)
                        selected_files.append(rel_path)
                        selected_in_this_pass = True
                        break
                
                if not lst:
                    active_lists.pop(token)
                    
            if not selected_in_this_pass:
                break

        top_files = selected_files
        logger.info(f"[DIAG] Calculated file_scores: {file_scores}")
        logger.info(f"Attempting to inject raw code for files: {top_files}")

        # Build file to matched line numbers mapping
        file_to_matched_lines = {}
        for tok, paths_dict in grep_hits.items():
            for rel_path, info in paths_dict.items():
                matched_lines = file_to_matched_lines.setdefault(rel_path, set())
                matched_lines.update(info.get("line_numbers", []))

        for rel_path in top_files:
            try:
                full_path = secure_path_join(self.target_repo_path, rel_path)
            except Exception as e:
                logger.error(f"Path verification failed for {rel_path}: {e}")
                continue

            if not (full_path.exists() and full_path.is_file()):
                logger.error(f"FAIL: File not found on disk at absolute path: {full_path}")
                continue

            ext = Path(rel_path).suffix.lower()
            is_source = ext in {'.py', '.js', '.jsx', '.ts', '.tsx', '.go', '.rs', '.c', '.cpp', '.h', '.java', '.kt', '.sh', '.pyw', '.rb', '.pl', '.pm', '.php', '.sql'}
            file_size = full_path.stat().st_size

            try:
                lines = (await asyncio.to_thread(full_path.read_text, encoding="utf-8")).splitlines()
            except Exception as e:
                logger.error(f"FAIL: Could not read source file {full_path}: {e}")
                continue

            # Fetch class/function AST nodes matching this file path
            file_ast_nodes = []
            for node_id, node_data in G.nodes(data=True):
                if node_data.get("file_path") == rel_path and node_data.get("type") in ["class", "function"]:
                    file_ast_nodes.append((node_id, node_data))

            # HTML, JSON or unstructured flat script files logic
            if not is_source or not file_ast_nodes:
                if (ext == ".json" and file_size < 5 * 1024) or (is_source and file_size < 20 * 1024):
                    code_content = "\n".join(lines)
                    clean_ext = ext.lstrip(".")
                    context_lines.append(f"\n### File: {rel_path}\n```{clean_ext}\n{code_content}\n```")
                    logger.info(f"SUCCESS: Injected full flat/config file: {full_path}")
                else:
                    matched_lines = file_to_matched_lines.get(rel_path, set())
                    if not matched_lines:
                        snippet_code = "\n".join(lines[:30])
                        clean_ext = ext.lstrip(".")
                        context_lines.append(f"\n### Preview of {rel_path} (First 30 lines)\n```{clean_ext}\n{snippet_code}\n```")
                        logger.info(f"SUCCESS: Injected snippet preview of {full_path}")
                    else:
                        sorted_lines = sorted(list(matched_lines))
                        chunks = []
                        curr_chunk = [sorted_lines[0]]
                        for l in sorted_lines[1:]:
                            if l - curr_chunk[-1] <= 5:
                                curr_chunk.append(l)
                            else:
                                chunks.append(curr_chunk)
                                curr_chunk = [l]
                        chunks.append(curr_chunk)

                        window = 15 if is_source else 5
                        for chunk in chunks:
                            start_l = max(1, min(chunk) - window)
                            end_l = min(len(lines), max(chunk) + window)
                            snippet_code = "\n".join(lines[start_l - 1:end_l])
                            clean_ext = ext.lstrip(".")
                            context_lines.append(f"\n### Code snippet from {rel_path} (Lines {start_l}-{end_l})\n```{clean_ext}\n{snippet_code}\n```")
                        logger.info(f"SUCCESS: Injected snippets for flat/config file: {full_path}")
                continue

            # Structured files: extract exact matching AST ranges
            matched_ast_nodes = set()
            matched_lines = file_to_matched_lines.get(rel_path, set())

            for node_id, node_data in file_ast_nodes:
                node_name = node_data.get("name", "")
                if node_name and any(tok.lower() in node_name.lower() for tok in tokens):
                    matched_ast_nodes.add((node_id, tuple(node_data.items())))
                    continue

                start = node_data.get("line_start", 0)
                end = node_data.get("line_end", 0)
                for line_no in matched_lines:
                    if start <= line_no <= end:
                        matched_ast_nodes.add((node_id, tuple(node_data.items())))
                        break

            if not matched_ast_nodes:
                for node_id, node_data in file_ast_nodes:
                    matched_ast_nodes.add((node_id, tuple(node_data.items())))

            sorted_nodes = sorted(list(matched_ast_nodes), key=lambda x: dict(x[1]).get("line_start", 0))
            for node_id, node_tuple in sorted_nodes:
                node_data = dict(node_tuple)
                node_type = node_data.get("type", "unknown")
                start = max(1, node_data.get("line_start", 1))
                end = min(len(lines), node_data.get("line_end", len(lines)))
                node_code = "\n".join(lines[start - 1:end])
                clean_ext = ext.lstrip(".")
                context_lines.append(f"\n### Code for [{node_type.upper()}] {node_id} (Lines {start}-{end})\n```{clean_ext}\n{node_code}\n```")
                logger.info(f"SUCCESS: Injected AST node {node_id} from {full_path}")

            # Grab global module-level context outside class/function scopes
            global_matched_lines = set()
            for line_no in matched_lines:
                inside_node = False
                for node_id, node_data in file_ast_nodes:
                    if node_data.get("line_start", 0) <= line_no <= node_data.get("line_end", 0):
                        inside_node = True
                        break
                if not inside_node:
                    global_matched_lines.add(line_no)

            if global_matched_lines:
                sorted_lines = sorted(list(global_matched_lines))
                chunks = []
                curr_chunk = [sorted_lines[0]]
                for l in sorted_lines[1:]:
                    if l - curr_chunk[-1] <= 3:
                        curr_chunk.append(l)
                    else:
                        chunks.append(curr_chunk)
                        curr_chunk = [l]
                chunks.append(curr_chunk)

                for chunk in chunks:
                    start_l = max(1, min(chunk) - 5)
                    end_l = min(len(lines), max(chunk) + 5)
                    snippet_code = "\n".join(lines[start_l - 1:end_l])
                    clean_ext = ext.lstrip(".")
                    context_lines.append(f"\n### Code snippet from {rel_path} (Lines {start_l}-{end_l})\n```{clean_ext}\n{snippet_code}\n```")
                logger.info(f"SUCCESS: Injected global/module-level snippets for {full_path}")

        return context_lines


    @timeit
    async def _build_context_payload(self, user_query: str, chat_history: str = "") -> str:
        """
        Orchestrates semantic, structural, and exact match searches to construct
        a dense codebase context payload.
        """
        try:
            G = await self._load_graph()
        except Exception as e:
            logger.error(f"Failed to load graph database: {e}")
            raise FileNotFoundError("Graph database not found.")

        filtered_G, relevance_scores = await self._get_relevant_subgraph(G=G, query=user_query, chat_history=chat_history)

        context_lines = ["# Codebase Semantic Map\n", "## Components & Logic"]

        # 1. Add Semantic Summaries
        context_lines.extend(self._extract_semantic_summaries(filtered_G))

        # 2. Automated Structural AST Search
        structural_findings = self._run_structural_ast_search(user_query, G)
        if structural_findings:
            context_lines.append("\n## Structural AST Queries")
            context_lines.extend(structural_findings)

        # 3. Add Structural Relationships
        context_lines.append("\n## Structural Relationships")
        context_lines.extend(self._extract_relationships(filtered_G))

        # 4. Dynamic File & Code Snippet Injection
        context_lines.append("\n## Relevant Raw Source Code")
        tokens = await self._extract_search_tokens_via_llm(user_query)
        raw_code_lines = await self._extract_raw_source_context(user_query, G, filtered_G, relevance_scores, tokens)
        context_lines.extend(raw_code_lines)

        return "\n".join(context_lines)


    async def _route_query(self, user_query: str, chat_history: str) -> str:
        """
        Decides if the user query is purely conversational or requires codebase context logic.
        """
        try:
            # A blazing fast, non-streaming call to get the routing word
            arguments = KernelArguments(
                chat_history=chat_history,
                user_query=user_query
            )
            decision = await self.kernel.invoke_prompt(prompt=ROUTER_PROMPT, arguments=arguments)
            decision_text = str(decision).strip().upper()
            
            if "CONVERSATIONAL" in decision_text:
                return "CONVERSATIONAL"
            return "CODEBASE"
        except Exception as e:
            logger.warning(f"Routing failed, defaulting to CODEBASE. Error: {e}")
            return "CODEBASE"
        
        
    @retry(wait=wait_exponential(multiplier=2, min=2, max=10), stop=stop_after_attempt(3), reraise=True)
    async def answer_question_stream(self, user_query: str, max_tokens: int = None, chat_history: str = ""):
        """Streams JSONL chunks, applies max_token limits, and captures telemetry."""
        # 1. Ask the Traffic Cop
        intent = await self._route_query(user_query, chat_history)
        
        execution_settings = OpenAIChatPromptExecutionSettings(
            max_tokens=max_tokens if max_tokens and max_tokens > 0 else 16384
        )

        # 2. Branch the Logic based on the Agent's decision
        if intent == "CONVERSATIONAL":
            logger.info("Agent routed query to Conversational Memory (Bypassing GraphRAG).")
            
            chat_prompt = f"""You are a helpful conversational AI assistant. 
            Below is the transcript of your conversation with the user so far:
            
            --- START CONVERSATION LOG ---
            {chat_history}
            --- END CONVERSATION LOG ---
            
            The user just said: "{user_query}"
            
            Respond directly to the user's latest message. Use the conversation log above as your personal memory to understand context.
            """
            
            arguments = KernelArguments(settings=execution_settings)
            final_prompt = chat_prompt
            
        else:
            logger.info(f"Agent routed query to GraphRAG Engine: '{user_query}'")
            
            # Trigger the heavy Vector Search + PageRank pipeline
            graph_context = await self._build_context_payload(user_query=user_query, chat_history=chat_history)
            
            arguments = KernelArguments(
                graph_context=graph_context,
                chat_history=chat_history,
                user_query=user_query,
                settings=execution_settings)
            final_prompt = GRAPH_RAG_PROMPT
        
       
        try:
            # The ONE and ONLY inference loop
            async for chunks in self.kernel.invoke_prompt_stream(
                prompt=final_prompt,
                arguments=arguments
            ):
                chunk = chunks[0] if isinstance(chunks, list) else chunks
               
                # 1. LOG AND YIELD JSON CHUNK
                if chunk.content:
                    yield json.dumps({"type": "chunk", "content": chunk.content}) + "\n"
                   
                # 2. Dynamic Telemetry Extraction Strategy
                try:
                    try:
                        delta = getattr(chunk.inner_content.choices[0], "delta", None)
                        if delta:
                            # Handle both Pydantic model attribute and raw dictionary
                            reasoning = getattr(delta, "reasoning_content", None)
                            if not reasoning and isinstance(delta, dict):
                                reasoning = delta.get("reasoning_content")
                               
                            if reasoning:
                                # Stream it to the UI under a specific "thought" type
                                yield json.dumps({"type": "thought", "content": reasoning}) + "\n"
                    except Exception:
                        pass
                    metadata = getattr(chunk, 'metadata', {})
                   
                    timings = None
                    if hasattr(chunk, 'timings') and chunk.timings:
                        timings = chunk.timings
                    elif hasattr(chunk, 'inner_content') and chunk.inner_content:
                       timings = getattr(chunk.inner_content, 'timings', None)
                       
                    if not timings and isinstance(chunk.inner_content, dict):
                            timings = chunk.inner_content.get('timings')
                    elif metadata and 'timings' in metadata:
                        timings = metadata['timings']

                    if timings:
                        tps = timings.get('predicted_per_second', 0) if isinstance(timings, dict) else getattr(timings, 'predicted_per_second', 0)
                       
                        prompt_n = timings.get('prompt_n', 0) if isinstance(timings, dict) else getattr(timings, 'prompt_n', 0)
                        predicted_n = timings.get('predicted_n', 0) if isinstance(timings, dict) else getattr(timings, 'predicted_n', 0)
                        total_tokens = prompt_n + predicted_n
                       
                        time_taken = total_tokens / tps if tps > 0 else 0
                               
                        logger.info(f"[TELEMETRY] Query complete | Time Taken: {time_taken:.2f} | Speed: {tps:.2f} tokens/sec | Total Tokens: {total_tokens} ({prompt_n} prompt + {predicted_n} generated)")
                       
                        telemetry_payload = {
                            "type": "telemetry",
                            "time_taken": round(time_taken, 2),
                            "tps": round(tps, 2),
                            "total_tokens": total_tokens,
                            "prompt_n": prompt_n,
                            "predicted_n": predicted_n
                        }
                        yield json.dumps(telemetry_payload) + "\n"
                       
                except Exception as e:
                    logger.warning(f"Could not parse telemetry from chunk: {e}")

        except Exception as e:
            error_str = str(e)
            if "Connection error" in error_str or "ConnectError" in error_str or "Failed to connect" in error_str:
                logger.error("LLM Connection Refused: Ensure llama.cpp/Ollama/LM Studio is running and port is correct.")
                yield "\n\n🚨 **Connection Lost:** Cannot reach the local LLM server. Please check if your inference engine is running."
            else:
                logger.error(f"LLM Generation Error: {error_str}")
                yield f"\n\n⚠️ **Inference Error:** The LLM encountered an issue. Make sure your context window isn't overflowing."
