import os
import asyncio
import re
import shutil
import subprocess
import json
import networkx as nx
from semantic_kernel.functions import KernelArguments
from pathlib import Path
from tenacity import retry, wait_exponential, stop_after_attempt
from semantic_kernel.connectors.ai.open_ai import OpenAIChatPromptExecutionSettings

from config import settings
from utils.logger import get_logger
from utils.helper import timeit, validate_ingestion_path, secure_path_join
from intelligence_layer.kernel_client import LocalKernelFactory
from core.vector_operations import HybridVectorStore
from intelligence_layer.kernel_client import CodebaseSearchPlugin
from utils.global_cache import load_graph_cached
from utils.helper import get_ignore_spec
from intelligence_layer.prompts import GRAPH_RAG_PROMPT, AGENT_PROMPT

logger = get_logger()


def score_line_match(line: str, matched_word: str, file_path: str) -> float:
    """
    Scores the relevance of a line match based on the matched word/pattern and file type.
    """
    line_lower = line.lower()
    word_lower = matched_word.lower()
    
    # 1. Check file extension first
    ext = os.path.splitext(file_path)[1].lower()
    is_source_file = ext in {'.py', '.js', '.jsx', '.ts', '.tsx', '.go', '.rs', '.c', '.cpp', '.h', '.java', '.kt', '.sh', '.pyw', '.rb', '.pl', '.pm', '.php', '.sql'}
    
    # Base weight based on file type
    base_weight = 1.0 if is_source_file else 0.2
    
    # Apply demotion for prompts or docs files specifically
    if "prompt" in file_path.lower():
        base_weight *= 0.1
    
    # 2. Check if the line is a comment or docstring
    stripped = line.strip()
    is_comment = False
    
    # Common comment patterns
    if stripped.startswith('#') or stripped.startswith('//') or stripped.startswith('*') or stripped.startswith('/*') or stripped.startswith('autogenerated'):
        is_comment = True
    
    # Check if the matched word appears after a comment character
    if '#' in line:
        before_comment = line.split('#', 1)[0]
        if word_lower not in before_comment.lower():
            is_comment = True
    if '//' in line:
        before_comment = line.split('//', 1)[0]
        if word_lower not in before_comment.lower():
            is_comment = True

    # 3. Check if it is inside quotes (string literal)
    is_quoted = f"'{word_lower}'" in line_lower or f'"{word_lower}"' in line_lower
    
    # 4. Check for active code characteristics:
    is_active_code = False
    if is_source_file and not is_comment and not is_quoted:
        # Check patterns with word_lower
        patterns = [
            rf"\bimport\s+{re.escape(word_lower)}\b",
            rf"\bfrom\s+\S+\s+import\s+.*{re.escape(word_lower)}",
            rf"\bdef\s+{re.escape(word_lower)}\b",
            rf"\bclass\s+{re.escape(word_lower)}\b",
            rf"\b{re.escape(word_lower)}\s*\(",
            rf"\b{re.escape(word_lower)}\s*=",
            rf"\.\s*{re.escape(word_lower)}\b",  # e.g. cv2.HoughCircles
            rf"\b{re.escape(word_lower)}\s*as\s+\w+" # e.g. import networkx as nx
        ]
        if any(re.search(pat, line_lower) for pat in patterns):
            is_active_code = True
            
    # Calculate multiplier
    if is_active_code:
        multiplier = 1.0
    elif is_comment or is_quoted:
        multiplier = 0.15 if is_source_file else 0.05
    else:
        multiplier = 0.5 if is_source_file else 0.1
        
    return base_weight * multiplier


class GraphQueryEngine:
    def __init__(self, repo_name: str, target_repo_path: str):
        self.repo_name = repo_name
        self.graph_path = f".localgraph/storage/{repo_name}/graph.graphml"
        self.kernel = LocalKernelFactory.create_kernel()
        self.kernel.add_plugin(CodebaseSearchPlugin(self), plugin_name="Codebase")
        self.vector_store = HybridVectorStore(repo_name)
        self.target_repo_path = str(validate_ingestion_path(target_repo_path))
        
        # Enable caching for faster query result
        self._graph_cache = None
        self._graph_mtime = None
   
   
    def _exact_match_search(
        self,
        query: str,
        target_dir: Path,
        ignore_spec,
    ) -> dict:
        """
        Extracts code-like tokens from the natural language query and
        searches for them literally or via split-regex across the workspace.
        Returns {token: {relative_path: {"line_numbers": [line_numbers], "match_score": float}}}.
        Respects the same ignore spec as ingestion.
        Language-agnostic: operates on raw file bytes regardless of language.
        """
        # Common English stop words to filter out from natural language queries
        stopwords = {
            "why", "is", "my", "chatbot", "not", "find", "any", "mentions", "of", 
            "despite", "me", "adding", "regex", "search", "in", "whole", "code", 
            "base", "can", "you", "see", "where", "the", "does", "do", "how", "what", 
            "which", "who", "whom", "this", "that", "these", "those", "am", "are", 
            "was", "were", "be", "been", "being", "have", "has", "had", "having", 
            "a", "an", "and", "but", "if", "or", "because", "as", "until", "while", 
            "at", "by", "for", "with", "about", "against", "between", "into", "through", 
            "during", "before", "after", "above", "below", "to", "from", "up", "down", 
            "on", "off", "over", "under", "again", "further", "then", "once", "here", 
            "there", "when", "all", "both", "each", "few", "more", "most", "other", 
            "some", "such", "no", "nor", "only", "own", "same", "so", "than", "too", 
            "very", "will", "just", "should", "now", "us", "use", "used", "using",
            "tell", "give", "code", "related", "write", "show", "get", "find", "make", 
            "explain", "describe", "detail", "summary", "list", "check", "verify", 
            "run", "execute", "test", "implementation", "implement", "add", "change", 
            "create", "delete", "remove", "update", "modify", "patch", "fix", "bug", 
            "issue", "error", "exception", "crash", "fail", "failure", "success", 
            "work", "can", "could", "should", "would", "must", "may", "might", "shall", 
            "please", "thanks", "thank", "hello", "hi", "hey", "dear", "sir", "madam", 
            "ai", "assistant", "bot", "chat", "chatbot", "history", "message", "query", 
            "question", "input", "output", "result", "response", "answer", "context", 
            "payload", "file", "folder", "directory", "repo", "repository", "workspace", 
            "codebase", "project", "source", "structure", "snippet", "snippets",
            "about", "also", "some", "someone", "something", "somewhere", "anyone",
            "anything", "anywhere", "noone", "nothing", "nowhere", "everyone", 
            "everything", "everywhere", "more", "most", "less", "least", "few", 
            "many", "several", "much", "little", "own", "other", "another", "such",
            "different", "similar", "like", "as", "than", "too", "very", "quite", 
            "rather", "somewhat", "highly", "extremely", "really"
        }

        # 1. First, extract code-specific patterns (CamelCase, snake_case, dotted names)
        code_tokens = re.findall(
            r'\b[A-Z][a-z]+(?:[A-Z][a-z0-9]+)+\b'     # CamelCase
            r'|\b[a-z][a-z0-9]*(?:_[a-z0-9]+)+\b'      # snake_case
            r'|\b[a-zA-Z_]\w+\.[a-zA-Z_]\w+\b',         # dotted
            query
        )

        # 2. As a fallback, extract any alphanumeric word that isn't a stopword or too short
        all_words = re.findall(r'\b[a-zA-Z_]\w*\b', query)
        fallback_tokens = [w for w in all_words if w.lower() not in stopwords and len(w) > 2]

        tokens = list(set(code_tokens + fallback_tokens))

        if not tokens:
            return {}

        has_rg  = shutil.which("rg") is not None
        results = {}

        for token in tokens:
            matched_lines = []

            # Generate fuzzy split regexes for compound/science words
            split_regex = ""
            if len(token) >= 6 and token.isalnum():
                mid = len(token) // 2
                splits = []
                for idx in range(max(3, mid - 1), min(len(token) - 2, mid + 2)):
                    part1 = token[:idx]
                    part2 = token[idx:]
                    splits.append(f"{re.escape(part1)}.*{re.escape(part2)}")
                split_regex = "|".join(splits)

            pattern = f"{re.escape(token)}|{split_regex}" if split_regex else re.escape(token)
            try:
                rx = re.compile(pattern, re.IGNORECASE)
            except Exception:
                rx = re.compile(re.escape(token), re.IGNORECASE)

            if has_rg:
                try:
                    if split_regex:
                        # Run regex search
                        out = subprocess.check_output(
                            ["rg", "-in", "--no-heading", pattern, str(target_dir)],
                            text=True,
                            timeout=5,
                            stderr=subprocess.DEVNULL
                        )
                    else:
                        # Run literal search
                        out = subprocess.check_output(
                            ["rg", "-in", "--no-heading", "-F", token, str(target_dir)],
                            text=True,
                            timeout=5,
                            stderr=subprocess.DEVNULL
                        )
                    matched_lines = out.strip().splitlines()
                except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
                    matched_lines = []
            else:
                # Pure-Python fallback — case-insensitive match
                for file_path in target_dir.rglob("*"):
                    if not file_path.is_file():
                        continue
                    try:
                        rel = str(file_path.relative_to(target_dir))
                    except ValueError:
                        continue
                    if ignore_spec.match_file(rel):
                        continue
                    try:
                        content = file_path.read_text(encoding="utf-8", errors="ignore")
                        for i, line in enumerate(content.splitlines(), 1):
                            matched = False
                            matched_word = token
                            if rx:
                                m = rx.search(line)
                                if m:
                                    matched = True
                                    matched_word = m.group(0)
                            else:
                                if token.lower() in line.lower():
                                    matched = True
                            if matched:
                                matched_lines.append(f"{file_path}:{i}:{line}")
                    except Exception:
                        continue

            token_results = {}
            for raw in matched_lines:
                parts = raw.split(":", 2)
                if len(parts) < 2:
                    continue
                try:
                    abs_path = Path(parts[0])
                    line_no  = int(parts[1])
                    rel_path = str(abs_path.relative_to(target_dir))
                except (ValueError, Exception):
                    continue
                if ignore_spec.match_file(rel_path):
                    continue

                line_content = parts[2] if len(parts) >= 3 else ""
                matched_word = token
                if line_content and rx:
                    m = rx.search(line_content)
                    if m:
                        matched_word = m.group(0)

                line_score = score_line_match(line_content, matched_word, rel_path)
                file_info = token_results.setdefault(rel_path, {"line_numbers": [], "match_score": 0.0})
                file_info["line_numbers"].append(line_no)
                file_info["match_score"] = max(file_info["match_score"], line_score)
            
            if token_results:
                results[token] = token_results

        return results
        
    def _get_relevant_subgraph(self, G: nx.Graph, query: str, chat_history: str = "", top_k: int = 15) -> tuple[nx.Graph, dict]:
        search_query = query
        if chat_history:
            context_anchor = chat_history[-150:].replace('\n', ' ')
            search_query = f"{context_anchor} {query}"
            logger.info(f"Enriched Vector Search Query: {search_query}")

        # 1. True Hybrid Search (RRF handles the exact-match heavy lifting now!)
        top_semantic_nodes = self.vector_store.search(search_query, top_k=top_k)
        
        seed_nodes = {}
        for rank, node_id in enumerate(top_semantic_nodes):
            # The #1 result gets highest score, scaling down linearly
            seed_nodes[node_id] = float(len(top_semantic_nodes) - rank)

        if not seed_nodes:
            logger.info("No direct matches found. Extracting central architectural hubs.")
            hub_nodes = sorted(G.degree, key=lambda x: x[1], reverse=True)[:top_k]
            subgraph_nodes = {node for node, _ in hub_nodes}
            scores = {node: float(deg) for node, deg in hub_nodes}
            for node in list(subgraph_nodes):
                neighbors = (set(G.successors(node)) | set(G.predecessors(node))) if G.is_directed() else set(G.neighbors(node))
                subgraph_nodes.update(neighbors)
                for n in neighbors:
                    scores.setdefault(n, 1.0)
            return G.subgraph(subgraph_nodes), scores

        total_score = sum(seed_nodes.values())
        personalization = {node: score / total_score for node, score in seed_nodes.items()}

        try:
            calc_graph = nx.DiGraph(G) if G.is_directed() else nx.Graph(G) if G.is_multigraph() else G
            pr_scores = nx.pagerank(calc_graph, alpha=0.85, personalization=personalization, max_iter=100)

            target_expansion_limit = top_k * 3
            top_structural_nodes = sorted(pr_scores, key=pr_scores.get, reverse=True)[:target_expansion_limit]
            subgraph_nodes = set(top_structural_nodes)
            scores = {n: pr_scores.get(n, 0) for n in subgraph_nodes}
            
            logger.info(f"Successfully generated structural PPR subgraph with {len(subgraph_nodes)} nodes.")
            return G.subgraph(subgraph_nodes), scores

        except Exception as e:
            logger.warning(f"PageRank computation failed or bypassed: {e}. Falling back to 1-hop neighborhood.")
            top_nodes = sorted(seed_nodes, key=seed_nodes.get, reverse=True)[:top_k]
            subgraph_nodes = set(top_nodes)
            scores = {n: seed_nodes.get(n, 0) for n in top_nodes}
            for node in top_nodes:
                neighbors = (set(G.successors(node)) | set(G.predecessors(node))) if G.is_directed() else set(G.neighbors(node))
                subgraph_nodes.update(neighbors)
                for n in neighbors:
                    scores.setdefault(n, 0.1)
            return G.subgraph(subgraph_nodes), scores
        
        
    async def _load_graph(self):
        return await load_graph_cached(self.graph_path)
   
   
    @timeit
    async def _build_context_payload(self, user_query: str, chat_history: str = "") -> str:
        target_dir = Path(self.target_repo_path)
        
        try:
            G = await self._load_graph()
        except Exception as e:
            logger.error(f"Failed to load graph database: {e}")
            raise FileNotFoundError("Graph database not found.")

        # filtered_G = self._get_relevant_subgraph(G=G, query=user_query, chat_history=chat_history)
        filtered_G, relevance_scores = self._get_relevant_subgraph(G=G, query=user_query, chat_history=chat_history)

        context_lines = ["# Codebase Semantic Map\n", "## Components & Logic"]
       
        # 1. Add the Semantic Summaries
        for node_id, data in filtered_G.nodes(data=True):
            if summary := data.get("summary", ""):
                context_lines.append(f"- [{data.get('type', 'unknown').upper()}] {node_id}: {summary}")

        context_lines.append("\n## Structural Relationships")
        for source, target, data in filtered_G.edges(data=True):
            context_lines.append(f"- {source} explicitly {data.get('relation', 'unknown')} {target}")

        # --- DYNAMIC FILE INJECTION ---
        context_lines.append("\n## Relevant Raw Source Code")
       
        file_scores = {}
        for node_id, node_data in filtered_G.nodes(data=True):
            file_path = node_data.get("file_path")
            if not file_path:
                node_str = str(node_id)
                if node_str.startswith("file::"):
                    file_path = node_str.replace("file::", "")
                elif "::" in node_str:
                    file_path = node_str.split("::")[0]
            if not file_path:
                continue

            file_path = str(file_path).strip()
            relevance = relevance_scores.get(node_id, 0.0)
            exact_bonus = 50 if user_query.lower() in str(node_id).lower() else 0
            node_score = relevance + exact_bonus
            file_scores[file_path] = max(file_scores.get(file_path, 0), node_score)
            
        ignore_spec = get_ignore_spec(target_dir)
        grep_hits = self._exact_match_search(user_query, target_dir, ignore_spec)
        
        # 1. Group files and their scores by the query token they matched
        token_to_files = {}
        
        # "semantic" token for files with semantic relevance
        semantic_list = sorted(file_scores.items(), key=lambda x: x[1], reverse=True)
        if semantic_list:
            token_to_files["semantic"] = semantic_list
            
        for token, paths_dict in grep_hits.items():
            num_matching_files = len(paths_dict)
            if num_matching_files == 0:
                continue
            if num_matching_files <= 3:
                token_bonus = 300.0 / num_matching_files
            else:
                token_bonus = 100.0 / num_matching_files
            
            token_list = []
            for rel_path, info in paths_dict.items():
                base_score = file_scores.get(rel_path, 0.0)
                match_score = info["match_score"]
                score = base_score + token_bonus * match_score
                token_list.append((rel_path, score))
                # Update global file_scores for diagnostics
                file_scores[rel_path] = score
                
            token_list.sort(key=lambda x: x[1], reverse=True)
            token_to_files[token] = token_list

        # 2. Round-robin selection loop with score-based list sorting to select top 5 files
        selected_files = []
        selected_set = set()
        active_lists = {token: list(lst) for token, lst in token_to_files.items()}
        
        while len(selected_files) < 5 and active_lists:
            # Sort tokens by the score of their highest remaining file
            sorted_tokens = sorted(
                active_lists.keys(),
                key=lambda t: active_lists[t][0][1] if active_lists[t] else -1.0,
                reverse=True
            )
            
            selected_in_this_pass = False
            for token in sorted_tokens:
                if len(selected_files) >= 8:
                    break
                
                lst = active_lists[token]
                while lst:
                    rel_path, score = lst.pop(0)
                    if rel_path not in selected_set:
                        selected_set.add(rel_path)
                        selected_files.append(rel_path)
                        selected_in_this_pass = True
                        break
                
                if not lst:
                    active_lists.pop(token)
                    
            if not selected_in_this_pass:
                break

        top_files = selected_files
        logger.info(f"[DIAG] Calculated file_scores: {file_scores}")
        # --- CRITICAL LOGGING ---
        logger.info(f"Attempting to inject raw code for files: {top_files}")
        for rel_path in top_files:
            try:
                full_path = secure_path_join(self.target_repo_path, rel_path)
            except Exception as e:
                logger.error(f"Path verification failed for {rel_path}: {e}")
                continue

            if full_path.exists() and full_path.is_file():
                try:
                    code_content = await asyncio.to_thread(full_path.read_text, encoding="utf-8")
                    # context_lines.append(f"\n### File: {rel_path}\n```python\n{code_content}\n```")
                    ext = Path(rel_path).suffix.lstrip(".")  # "py", "js", "java", etc.
                    context_lines.append(f"\n### File: {rel_path}\n```{ext}\n{code_content}\n```")
                    logger.info(f"SUCCESS: Injected physical file: {full_path}")
                except Exception as e:
                    logger.error(f"FAIL: Could not read source file {full_path}: {e}")
            else:
                logger.error(f"FAIL: File not found on disk at absolute path: {full_path}")

        return "\n".join(context_lines)
    

    async def _route_query(self, user_query: str, chat_history: str) -> str:
        """
        The Traffic Cop: Decides if we need to search the graph or just chat.
        """
        router_prompt = f"""You are an elite, high-speed routing engine for a local repository AI assistant.
            Your sole job is to classify the user's latest input into one of two routing destinations:

            1. 'CONVERSATIONAL': Choose this ONLY if the user is greeting you, making small talk, or asking meta-questions about the chat history itself (e.g., "What did I just ask?").
            2. 'CODEBASE': Choose this for anything else. 
            **CRITICAL OVERRIDE:** If the user asks an explanatory question like "How does X work?", "Why do we use Y?", or "What advantage does Z provide?", you MUST route to CODEBASE so the agent can read the repository files to find the answer.

            ---
            FEW-SHOT EXAMPLES:

            Input: "Hi there" -> Destination: CONVERSATIONAL
            Input: "What questions did I ask you so far?" -> Destination: CONVERSATIONAL
            Input: "Can you tell what advantage Data Normalizer did provide?" -> Destination: CODEBASE
            Input: "Why are we using a median blur here?" -> Destination: CODEBASE
            Input: "process_data_frame" -> Destination: CODEBASE
            Input: "thanks for the help" -> Destination: CONVERSATIONAL
            Input: "where is the threshold setting?" -> Destination: CODEBASE
            ---

            Current Chat History:
            {chat_history}

            Latest User Input: "{user_query}"

            Respond with EXACTLY one word, either 'CONVERSATIONAL' or 'CODEBASE'. Do not include punctuation, explanation, or markdown formatting.

            Destination:"""
            
        try:
            # A blazing fast, non-streaming call to get the routing word
            decision = await self.kernel.invoke_prompt(prompt=router_prompt)
            decision_text = str(decision).strip().upper()
            
            if "CONVERSATIONAL" in decision_text:
                return "CONVERSATIONAL"
            return "CODEBASE"
        except Exception as e:
            logger.warning(f"Routing failed, defaulting to CODEBASE. Error: {e}")
            return "CODEBASE"
        
        
    @retry(wait=wait_exponential(multiplier=2, min=2, max=10), stop=stop_after_attempt(3), reraise=True)
    async def answer_question_stream(self, user_query: str, max_tokens: int = None, chat_history: str = ""):
        """Streams JSONL chunks, applies max_token limits, and captures telemetry."""
        # 1. Ask the Traffic Cop
        intent = await self._route_query(user_query, chat_history)
        
        execution_settings = OpenAIChatPromptExecutionSettings(
            max_tokens=max_tokens if max_tokens and max_tokens > 0 else 16384
        )

        # 2. Branch the Logic based on the Agent's decision
        if intent == "CONVERSATIONAL":
            logger.info("Agent routed query to Conversational Memory (Bypassing GraphRAG).")
            
            chat_prompt = f"""You are a helpful conversational AI assistant. 
            Below is the transcript of your conversation with the user so far:
            
            --- START CONVERSATION LOG ---
            {chat_history}
            --- END CONVERSATION LOG ---
            
            The user just said: "{user_query}"
            
            Respond directly to the user's latest message. Use the conversation log above as your personal memory to understand context.
            """
            
            arguments = KernelArguments(settings=execution_settings)
            final_prompt = chat_prompt
            
        else:
            logger.info(f"Agent routed query to GraphRAG Engine: '{user_query}'")
            
            # Trigger the heavy Vector Search + PageRank pipeline
            graph_context = await self._build_context_payload(user_query=user_query, chat_history=chat_history)
            
            arguments = KernelArguments(
                graph_context=graph_context,
                chat_history=chat_history,
                user_query=user_query,
                settings=execution_settings)
            final_prompt = GRAPH_RAG_PROMPT
        
       
        try:
            # The ONE and ONLY inference loop
            async for chunks in self.kernel.invoke_prompt_stream(
                prompt=final_prompt,
                arguments=arguments
            ):
                chunk = chunks[0] if isinstance(chunks, list) else chunks
               
                # 1. LOG AND YIELD JSON CHUNK
                if chunk.content:
                    # --- NEW: PRINT DIRECTLY TO TERMINAL ---
                    # print(f"RAW: [{chunk.content}]", flush=True)
                   
                    yield json.dumps({"type": "chunk", "content": chunk.content}) + "\n"
                   
                # 2. Dynamic Telemetry Extraction Strategy
                try:
                    try:
                        delta = getattr(chunk.inner_content.choices[0], "delta", None)
                        if delta:
                            # Handle both Pydantic model attribute and raw dictionary
                            reasoning = getattr(delta, "reasoning_content", None)
                            if not reasoning and isinstance(delta, dict):
                                reasoning = delta.get("reasoning_content")
                               
                            if reasoning:
                                # Stream it to the UI under a specific "thought" type
                                yield json.dumps({"type": "thought", "content": reasoning}) + "\n"
                    except Exception:
                        pass
                    metadata = getattr(chunk, 'metadata', {})
                   
                    timings = None
                    if hasattr(chunk, 'timings') and chunk.timings:
                        timings = chunk.timings
                    elif hasattr(chunk, 'inner_content') and chunk.inner_content:
                       timings = getattr(chunk.inner_content, 'timings', None)
                       
                    if not timings and isinstance(chunk.inner_content, dict):
                            timings = chunk.inner_content.get('timings')
                    elif metadata and 'timings' in metadata:
                        timings = metadata['timings']

                    if timings:
                        tps = timings.get('predicted_per_second', 0) if isinstance(timings, dict) else getattr(timings, 'predicted_per_second', 0)
                       
                        prompt_n = timings.get('prompt_n', 0) if isinstance(timings, dict) else getattr(timings, 'prompt_n', 0)
                        predicted_n = timings.get('predicted_n', 0) if isinstance(timings, dict) else getattr(timings, 'predicted_n', 0)
                        total_tokens = prompt_n + predicted_n
                       
                        time_taken = total_tokens / tps if tps > 0 else 0
                               
                        logger.info(f"[TELEMETRY] Query complete | Time Taken: {time_taken:.2f} | Speed: {tps:.2f} tokens/sec | Total Tokens: {total_tokens} ({prompt_n} prompt + {predicted_n} generated)")
                       
                        telemetry_payload = {
                            "type": "telemetry",
                            "time_taken": round(time_taken, 2),
                            "tps": round(tps, 2),
                            "total_tokens": total_tokens,
                            "prompt_n": prompt_n,
                            "predicted_n": predicted_n
                        }
                        yield json.dumps(telemetry_payload) + "\n"
                       
                except Exception as e:
                    logger.warning(f"Could not parse telemetry from chunk: {e}")

        except Exception as e:
            # 1. Get a clean, stringified version of the error without the massive traceback
            error_str = str(e)
            
            # 2. Check if it's a connection-related death
            if "Connection error" in error_str or "ConnectError" in error_str or "Failed to connect" in error_str:
                logger.error("LLM Connection Refused: Ensure llama.cpp/Ollama/LM Studio is running and port is correct.")
                yield "\n\n🚨 **Connection Lost:** Cannot reach the local LLM server. Please check if your inference engine is running."
            else:
                # 3. Handle context window overflows or other generation errors cleanly
                logger.error(f"LLM Generation Error: {error_str}")
                yield f"\n\n⚠️ **Inference Error:** The LLM encountered an issue. Make sure your context window isn't overflowing."

