from pydantic import BaseModel, Field
from typing import Optional

class QueryRequest(BaseModel):
    repo_name: str = Field(
        ..., 
        description="The exact name of the ingested repository workspace to query against.",
        examples=["Conv2dLSTM"]
    )
    question: str = Field(
        ..., 
        description="A natural language question regarding the codebase architecture, logic, or data flow.",
        examples=["If I pass a raw image array into the system, which class handles the normalization, and what math does it do?"]
    )
    max_tokens: Optional[int] = Field(
        default=None, 
        description="The maximum number of tokens the LLM is allowed to generate. If null, uses the model's maximum limit."
    )
    target_path: str = Field(
        ...,
        description="Target code location will be provided to LLM to provide relevant results."
    )

class QueryResponse(BaseModel):
    answer: str = Field(
        ..., 
        description="The detailed, technical answer generated by the LLM using the semantic graph map.",
        examples=["The `DataNormalizer` class handles the normalization. It uses the `process_tensor` method to divide the raw input array by 255.0."]
    )