from pydantic import BaseModel, Field

class QueryRequest(BaseModel):
    repo_name: str = Field(
        ..., 
        description="The exact name of the ingested repository workspace to query against.",
        examples=["Conv2dLSTM"]
    )
    question: str = Field(
        ..., 
        description="A natural language question regarding the codebase architecture, logic, or data flow.",
        examples=["If I pass a raw image array into the system, which class handles the normalization, and what math does it do?"]
    )

class QueryResponse(BaseModel):
    answer: str = Field(
        ..., 
        description="The detailed, technical answer generated by the LLM using the semantic graph map.",
        examples=["The `DataNormalizer` class handles the normalization. It uses the `process_tensor` method to divide the raw input array by 255.0."]
    )