"""
Defines Pydantic schemas for codebase queries and search requests, 
including API query payloads, node chats, and AST structural queries.
"""

from pydantic import BaseModel, Field
from typing import Optional, Annotated, Dict, Any


RepoName = Annotated[
    str,
    Field(
        pattern=r"^[a-zA-Z0-9_-]+$",
        min_length=1,
        max_length=100
    )
]


class QueryRequest(BaseModel):
    repo_name: RepoName = Field(
        ..., 
        description="The exact name of the ingested repository workspace to query against.",
        examples=["Conv2dLSTM"]
    )
    question: str = Field(
        ..., 
        description="A natural language question regarding the codebase architecture, logic, or data flow.",
        examples=["If I pass a raw image array into the system, which class handles the normalization, and what math does it do?"]
    )
    max_tokens: Optional[int] = Field(
        default=None, 
        description="The maximum number of tokens the LLM is allowed to generate. If null, uses the model's maximum limit."
    )
    target_path: str = Field(
        ...,
        description="Target code location will be provided to LLM to provide relevant results."
    )
    chat_history: Optional[str] = ""


class QueryResponse(BaseModel):
    answer: str = Field(
        ..., 
        description="The detailed, technical answer generated by the LLM using the semantic graph map.",
        examples=["The `DataNormalizer` class handles the normalization. It uses the `process_tensor` method to divide the raw input array by 255.0."]
    )


class NodeChatRequest(BaseModel):
    node_id: str = Field(
        ...,
        description="Node on which the question is being asked"
    )
    question: str = Field(
        ...,
        description="Question asked by user regarding the node."
    )
    target_path: str = Field(
        ..., 
        description="Provides target path to LLM to get to code"
    )


class ASTSearchRequest(BaseModel):
    repo_name: str = Field(
        ...,
        description="Name of the repository to search"
    )
    target_path: str = Field(
        ...,
        description="Path of the workspace target directory"
    )
    query_type: str = Field(
        ...,
        description="Search mode: 'graph' or 'tree-sitter'"
    )
    filters: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Graph filters (node_type, name substring, class inheritance, calls relations)"
    )
    pattern: Optional[str] = Field(
        default=None,
        description="Tree-sitter pattern template or custom S-expression query"
    )
    language_ext: Optional[str] = Field(
        default=None,
        description="Source code language extension (e.g. .py, .ts)"
    )